# Generated by Django 4.0.4 on 2022-05-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'scrap_url')},
        ),
    ]
